/**
 * techMap: A mapping of technology keywords to Devicon CSS classes.
 * * Usage:
 * <i className={techMap['react']}></i>
 * * Note: Ensure the Devicon CDN link is included in your HTML head.
 */
export const techMap: { [key: string]: string } = {
  // --- CORE LANGUAGES ---
  javascript: "devicon-javascript-plain",
  js: "devicon-javascript-plain",
  typescript: "devicon-typescript-plain",
  ts: "devicon-typescript-plain",
  html: "devicon-html5-plain",
  html5: "devicon-html5-plain",
  css: "devicon-css3-plain",
  css3: "devicon-css3-plain",
  python: "devicon-python-plain",
  java: "devicon-java-plain",
  php: "devicon-php-plain",
  ruby: "devicon-ruby-plain",
  go: "devicon-go-plain",
  rust: "devicon-rust-plain",
  swift: "devicon-swift-plain",
  kotlin: "devicon-kotlin-plain",
  dart: "devicon-dart-plain",
  c: "devicon-c-plain",
  cpp: "devicon-cplusplus-plain",
  "c++": "devicon-cplusplus-plain",
  csharp: "devicon-csharp-plain",
  "c#": "devicon-csharp-plain",
  scala: "devicon-scala-plain",
  elixir: "devicon-elixir-plain",
  haskell: "devicon-haskell-plain",
  zig: "devicon-zig-plain",
  perl: "devicon-perl-plain",
  lua: "devicon-lua-plain",
  clojure: "devicon-clojure-line",

  // --- FRONTEND FRAMEWORKS & TOOLS ---
  react: "devicon-react-original",
  reactjs: "devicon-react-original",
  nextjs: "devicon-nextjs-plain",
  next: "devicon-nextjs-plain",
  vue: "devicon-vuejs-plain",
  vuejs: "devicon-vuejs-plain",
  angular: "devicon-angularjs-plain",
  svelte: "devicon-svelte-plain",
  astro: "devicon-astro-plain",
  solidjs: "devicon-solidjs-plain",
  remix: "devicon-remix-plain",
  nuxt: "devicon-nuxtjs-plain",
  jquery: "devicon-jquery-plain",
  tailwind: "devicon-tailwindcss-plain",
  tailwindcss: "devicon-tailwindcss-plain",
  bootstrap: "devicon-bootstrap-plain",
  sass: "devicon-sass-plain",
  less: "devicon-less-plain-wordmark",
  threejs: "devicon-threejs-original",
  redux: "devicon-redux-original",
  babel: "devicon-babel-plain",
  webpack: "devicon-webpack-plain",
  vite: "devicon-vitejs-plain",

  // --- BACKEND & RUNTIMES ---
  nodejs: "devicon-nodejs-plain",
  node: "devicon-nodejs-plain",
  bun: "devicon-bun-plain",
  deno: "devicon-denojs-plain",
  express: "devicon-express-original",
  nestjs: "devicon-nestjs-plain",
  fastapi: "devicon-fastapi-plain",
  django: "devicon-django-plain",
  flask: "devicon-flask-original",
  laravel: "devicon-laravel-plain",
  rails: "devicon-rails-plain",
  spring: "devicon-spring-plain",
  graphql: "devicon-graphql-plain",
  apollo: "devicon-apollographql-plain",

  // --- MOBILE & CROSS-PLATFORM ---
  flutter: "devicon-flutter-plain",
  reactnative: "devicon-react-original", // React logo usually used
  android: "devicon-android-plain",
  apple: "devicon-apple-original",
  ionic: "devicon-ionic-original",
  capacitor: "devicon-capacitor-plain",
  unity: "devicon-unity-original",
  unrealengine: "devicon-unrealengine-original",

  // --- DATABASES ---
  mongodb: "devicon-mongodb-plain",
  mongo: "devicon-mongodb-plain",
  postgresql: "devicon-postgresql-plain",
  postgres: "devicon-postgresql-plain",
  mysql: "devicon-mysql-plain",
  sqlite: "devicon-sqlite-plain",
  redis: "devicon-redis-plain",
  firebase: "devicon-firebase-plain",
  supabase: "devicon-supabase-plain",
  cassandra: "devicon-cassandra-plain",
  mariadb: "devicon-mariadb-plain",
  elasticsearch: "devicon-elasticsearch-plain",

  // --- DEVOPS & CLOUD ---
  docker: "devicon-docker-plain",
  kubernetes: "devicon-kubernetes-plain",
  k8s: "devicon-kubernetes-plain",
  git: "devicon-git-plain",
  github: "devicon-github-original",
  gitlab: "devicon-gitlab-plain",
  bitbucket: "devicon-bitbucket-plain",
  aws: "devicon-amazonwebservices-original",
  amazonwebservices: "devicon-amazonwebservices-original",
  azure: "devicon-azure-plain",
  gcp: "devicon-googlecloud-plain",
  googlecloud: "devicon-googlecloud-plain",
  terraform: "devicon-terraform-plain",
  jenkins: "devicon-jenkins-plain",
  nginx: "devicon-nginx-plain",
  prometheus: "devicon-prometheus-plain",
  grafana: "devicon-grafana-plain",
  ansible: "devicon-ansible-plain",
  linux: "devicon-linux-plain",
  ubuntu: "devicon-ubuntu-plain",
  debian: "devicon-debian-plain",

  // --- DESIGN & TOOLS ---
  figma: "devicon-figma-plain",
  photoshop: "devicon-photoshop-plain",
  illustrator: "devicon-illustrator-plain",
  xd: "devicon-xd-plain",
  aftereffects: "devicon-aftereffects-plain",
  premierepro: "devicon-premierepro-plain",
  blender: "devicon-blender-plain",
  vscode: "devicon-vscode-plain",
  webstorm: "devicon-webstorm-plain",
  pycharm: "devicon-pycharm-plain",
  intellij: "devicon-intellij-plain",
  vim: "devicon-vim-plain",
  postman: "devicon-postman-plain",
  insomnia: "devicon-insomnia-plain",
  trello: "devicon-trello-plain",
  jira: "devicon-jira-plain",

  // --- DATA SCIENCE & AI ---
  numpy: "devicon-numpy-plain",
  pandas: "devicon-pandas-plain",
  tensorflow: "devicon-tensorflow-line",
  pytorch: "devicon-pytorch-plain",
  opencv: "devicon-opencv-plain",
  jupyter: "devicon-jupyter-plain",
  matlab: "devicon-matlab-plain",
  r: "devicon-r-original",

  // --- OTHERS FROM LIST ---
  algolia: "devicon-algolia-original",
  arduino: "devicon-arduino-plain",
  bash: "devicon-bash-plain",
  chrome: "devicon-chrome-plain",
  discordjs: "devicon-discordjs-plain",
  heroku: "devicon-heroku-plain",
  netlify: "devicon-netlify-plain",
  vercel: "devicon-vercel-original",
  yarn: "devicon-yarn-plain",
  npm: "devicon-npm-original-wordmark",
  pnpm: "devicon-pnpm-plain",
};